name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref	 }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check for linting
        run: yarn dev:check
